[LiveConfigs]
BigFontName=Arial
[Notes]
Type=2
Lock=0
BigFontName=Arial
WrapText=0
Action_help_file="C:\Users\Studio\AppData\Roaming\REAPER\S&M_Action_help_en.ini"
[RegionPlaylist]
MonitorMode=0
Repeat=0
SeekImmediate=0
SeekPlay=0
BigFontName=Arial
ShufflePlaylist=0
[Cyclactions]
Undos=1
PreventUIRefresh=1
[ImageView]
Stretch=0
[CueBuss1]
name=""
reatype=0
track_template_enabled=0
track_template_path=""
show_routing=1
send_to_masterparent=0
solo_defeat=0
[Misc]
RemoveAllEnvsSelTracksPrompt=1
[Resources]
Type=5
Filter=1
AutoFillDirFXChains="C:\Users\Studio\AppData\Roaming\REAPER\FXChains"
AutoSaveDirFXChains="C:\Users\Studio\AppData\Roaming\REAPER\FXChains"
SyncAutoDirsFXChains=1
TiedActionsFXChains=0
DblClickFXChains=0
AutoSaveFXChain=0
AutoSaveFXChainName=0
AutoFillDirTrackTemplates="C:\Users\Studio\AppData\Roaming\REAPER\TrackTemplates"
AutoSaveDirTrackTemplates="C:\Users\Studio\AppData\Roaming\REAPER\TrackTemplates"
SyncAutoDirsTrackTemplates=1
TiedActionsTrackTemplates=1
DblClickTrackTemplates=0
AutoSaveTrTemplate=3
AutoFillDirProjectTemplates="C:\Users\Studio\AppData\Roaming\REAPER\ProjectTemplates"
AutoSaveDirProjectTemplates="C:\Users\Studio\AppData\Roaming\REAPER\ProjectTemplates"
SyncAutoDirsProjectTemplates=1
TiedActionsProjectTemplates=2
DblClickProjectTemplates=0
AutoFillDirMediaFiles="C:\Users\Studio\AppData\Roaming\REAPER\MediaFiles"
AutoSaveDirMediaFiles="C:\Users\Studio\AppData\Roaming\REAPER\MediaFiles"
SyncAutoDirsMediaFiles=1
TiedActionsMediaFiles=3
DblClickMediaFiles=0
AddMediaFileOptions=0
AutoFillDirTrack_icons="C:\Users\Studio\AppData\Roaming\REAPER\Data\track_icons"
SyncAutoDirsTrack_icons=0
TiedActionsTrack_icons=4
DblClickTrack_icons=0
AutoFillDirColorThemes="C:\Users\Studio\AppData\Roaming\REAPER\ColorThemes"
SyncAutoDirsColorThemes=0
TiedActionsColorThemes=5
DblClickColorThemes=0
[FXChains]
Max_slot=0
[TrackTemplates]
Max_slot=0
[ProjectTemplates]
Max_slot=0
[MediaFiles]
Max_slot=0
[Track_icons]
Max_slot=91
Slot1="ac_guitar.png"
Slot2="ac_guitar_full.png"
Slot3="amp.png"
Slot4="amp_combo.png"
Slot5="balalaika.png"
Slot6="banjo.png"
Slot7="bass.png"
Slot8="bass2.png"
Slot9="bass3.png"
Slot10="bass4.png"
Slot11="bass_clef.png"
Slot12="bass_full.png"
Slot13="beats.png"
Slot14="bin.png"
Slot15="bongos.png"
Slot16="cabasa.png"
Slot17="cello.png"
Slot18="congas.png"
Slot19="cowbell.png"
Slot20="cowbell_more.png"
Slot21="cymbal_large.png"
Slot22="cymbal_small.png"
Slot23="deck.png"
Slot24="double_bass.png"
Slot25="drumbox.png"
Slot26="drums.png"
Slot27="envelope.png"
Slot28="female.png"
Slot29="female_head.png"
Slot30="ff.png"
Slot31="film.png"
Slot32="folder.png"
Slot33="folder_down.png"
Slot34="folder_left.png"
Slot35="folder_right.png"
Slot36="folder_up.png"
Slot37="fx.png"
Slot38="group.png"
Slot39="guitar.png"
Slot40="guitar2.png"
Slot41="guitar3.png"
Slot42="guitar4.png"
Slot43="guitar5.png"
Slot44="guitar_full.png"
Slot45="harmonica.png"
Slot46="harp.png"
Slot47="hihat.png"
Slot48="idea.png"
Slot49="kick.png"
Slot50="male.png"
Slot51="male_head.png"
Slot52="maracas.png"
Slot53="meter.png"
Slot54="mic.png"
Slot55="mic_condenser_1.png"
Slot56="mic_condenser_2.png"
Slot57="mic_dynamic_1.png"
Slot58="mic_dynamic_2.png"
Slot59="mic_shotgun.png"
Slot60="midi.png"
Slot61="mixer.png"
Slot62="organ.png"
Slot63="overheads.png"
Slot64="pads.png"
Slot65="pedal.png"
Slot66="phones.png"
Slot67="piano.png"
Slot68="pp.png"
Slot69="reverb.png"
Slot70="ride_bell.png"
Slot71="ride_rim.png"
Slot72="room_large.png"
Slot73="room_medium.png"
Slot74="room_small.png"
Slot75="sax.png"
Slot76="snare_bottom.png"
Slot77="snare_top.png"
Slot78="speech.png"
Slot79="synth.png"
Slot80="synth2.png"
Slot81="synthbass.png"
Slot82="system.png"
Slot83="tamborine.png"
Slot84="tape.png"
Slot85="tom.png"
Slot86="treble_clef.png"
Slot87="trombone.png"
Slot88="trumpet.png"
Slot89="violin.png"
Slot90="xylophone.png"
Slot91="yeah_you_guys_are_great.png"
[ColorThemes]
Max_slot=3
Slot1="I Logic Ultimate Laptop.ReaperTheme"
Slot2="I Logic Ultimate Laptop Dark.ReaperTheme"
Slot3="I Logic Ultimate.ReaperTheme"
[General]
; REAPER v7.69/x64 ===
; SWS/S&M Extension v2.14.0 Build 7 ===
; C:\Users\Administrator\AppData\Roaming\REAPER\S&M.ini ===
IniFileUpgrade=9
MediaFileLockAudio=0
ToolbarsAutoRefresh=1
ToolbarsAutoRefreshFreq=300 ; in ms (min: 100, max: 5000)
BuggyPlugsSupport=0
ClearTypeFont=1
DiffTool=""
LearnPitchAndNormOSC=0
Beta=0
ExtensionsSubmenu=1
[NbOfActions]
; Set the number of actions you want below. Quit REAPER first! ===
; Unless specified, the maximum number of actions is 255 (0 will hide actions). ===
S&M_CUEBUS=8                             ; [Основная] Создать cue-шину из выбора трека, настройки n -- Max. = 8!
S&M_FXOFF_SETON=8                        ; [Основная] задать FX n выбранных треков режим онлайн
S&M_FXOFF_SETOFF=8                       ; [Основная] задать FX n выбранных треков режим офлайн
S&M_FXOFF=8                              ; [Основная] переключить FX n выбранных треков режим онлайн/офлайн
S&M_FXBYP_SETON=8                        ; [Основная] байпас FX n выбранных треков
S&M_FXBYP_SETOFF=8                       ; [Основная] сбросить байпас FX n выбранных треков
S&M_FXBYP=8                              ; [Основная] переключить FX n выбранных треков в режим байпас
S&M_FXOFFEXCPT=0                         ; [Основная] переключить все FX выбранных треков (кроме n) в режим онлайн/офлайн
S&M_FXBYPEXCPT=0                         ; [Основная] переключить все FX выбранных треков (кроме n) в режим байпас
S&M_FXOFF_ALL_ON_EXCPT=0                 ; [Основная] задать всем FX выбранных треков (кроме n) режим онлайн
S&M_FXOFF_ALL_OFF_EXCPT=8                ; [Основная] задать всем FX выбранных треков (кроме n) режим оффлайн
S&M_FXBYP_ALL_ON_EXCPT=8                 ; [Основная] байпас всех FX выбранных треков (кроме n)
S&M_FXBYP_ALL_OFF_EXCPT=0                ; [Основная] сбросить байпас всех FX выбранных треков (кроме n)
S&M_CLRFXCHAINSLOT=0                     ; [Основная] ресурсы - очистить слот цепочки FX n
S&M_TAKEFXCHAIN=4                        ; [Основная] ресурсы - вставить (заменить) цепочку FX в выбранные айтемы, слот n
S&M_PASTE_TAKEFXCHAIN=4                  ; [Основная] ресурсы - вставить цепочку FX в выбранные айтемы, слот n
S&M_FXCHAIN_ALLTAKES=0                   ; [Основная] ресурсы - вставить (заменить) цепочку FX в выбранные айтемы, все дубли, слот n
S&M_PASTE_FXCHAIN_ALLTAKES=0             ; [Основная] ресурсы - вставить цепочку FX в выбранные айтемы, все дубли, слот n
S&M_TRACKFXCHAIN=4                       ; [Основная] ресурсы - вставить (заменить) цепочку FX в выбранные треки, слот n
S&M_PASTE_TRACKFXCHAIN=4                 ; [Основная] ресурсы - вставить цепочку FX в выбранные треки, слот n
S&M_INFXCHAIN=0                          ; [Основная] ресурсы - вставить (заменить) входную цепочку FX в выбранные треки, слот n
S&M_PASTE_INFXCHAIN=0                    ; [Основная] ресурсы - вставить входную цепочку FX в выбранные треки, слот n
S&M_REPLACE_TEMPLATE_ITEMS=4             ; [Основная] ресурсы - вставить (заменить) айтемы шаблона в выбранные треки, слот n
S&M_PASTE_TEMPLATE_ITEMS=4               ; [Основная] ресурсы - вставить айтемы шаблона в выбранные треки, слот n
S&M_CLR_TRTEMPLATE_SLOT=0                ; [Основная] ресурсы - очистить слот шаблона трека n
S&M_APPLY_TRTEMPLATE=4                   ; [Основная] ресурсы - применить шаблон трека к выбранным трекам, слот n
S&M_APPLY_TRTEMPLATE_ITEMSENVS=4         ; [Основная] ресурсы - применить шаблон трека (+огибающие/айтемы) к выбранным трекам, слот n
S&M_ADD_TRTEMPLATE=4                     ; [Основная] ресурсы - импорт треков из шаблона трека, слот n
S&M_CLR_PRJTEMPLATE_SLOT=0               ; [Основная] ресурсы - очистить слот проекта n
S&M_APPLY_PRJTEMPLATE=4                  ; [Основная] ресурсы - открыть проект, слот n
S&M_NEWTAB_PRJTEMPLATE=4                 ; [Основная] ресурсы - открыть проект, слот n (новая вкладка)
S&M_CLR_MEDIA_SLOT=0                     ; [Основная] ресурсы - очистить слот медиафайла n
S&M_PLAYMEDIA_SELTRACK=4                 ; [Основная] ресурсы - проиграть медиафайл выбранных треков, слот n
S&M_LOOPMEDIA_SELTRACK=4                 ; [Основная] ресурсы - запетлить медиафайл выбранных треков, слот n
S&M_PLAYMEDIA_SELTRACK_SYNC=4            ; [Основная] ресурсы - проиграть медиафайл выбранных треков (синхронизация со следующим тактом), слот n
S&M_LOOPMEDIA_SELTRACK_SYNC=4            ; [Основная] ресурсы - запетлить медиафайл выбранных треков (синхронизация со следующим тактом), слот n
S&M_TGL_PLAYMEDIA_SELTRACK=4             ; [Основная] ресурсы - проиграть медиафайл выбранных треков (переключить), слот n
S&M_TGL_LOOPMEDIA_SELTRACK=4             ; [Основная] ресурсы - запетлить медиафайл выбранных треков (переключить), слот n
S&M_TGLPAUSE_PLAYMEDIA_SELTR=4           ; [Основная] ресурсы - проиграть медиафайл выбранных треков (переключить паузу), слот n
S&M_TGLPAUSE_LOOPMEDIA_SELTR=0           ; [Основная] ресурсы - запетлить медиафайл выбранных треков (переключить паузу), слот n
S&M_ADDMEDIA_CURTRACK=4                  ; [Основная] ресурсы - добавить медиафайл на текущий трек, слот n
S&M_ADDMEDIA_NEWTRACK=4                  ; [Основная] ресурсы - добавить медиафайл на новый трек, слот n
S&M_ADDMEDIA_SELITEM=4                   ; [Основная] ресурсы - добавить медиафайл к выбранным айтемам как дубли, слот n
S&M_CLR_IMAGE_SLOT=0                     ; [Основная] Ресурсы - очистить слот изображения n
S&M_SHOW_IMG=4                           ; [Основная] ресурсы - показать изображение, слот n
S&M_SET_TRACK_ICON=4                     ; [Основная] ресурсы - задать значок дорожки выбранных треков, слот n
S&M_CLR_THEME_SLOT=0                     ; [Основная] ресурсы - очистить слот темы n
S&M_LOAD_THEME=4                         ; [Основная] ресурсы - загрузить тему, слот n
S&M_NEXT_PRESET_FX=4                     ; [Основная] запустить следующий пресет FX n выбранных треков
S&M_PREVIOUS_PRESET_FX=4                 ; [Основная] запустить предыдущий пресет FX n выбранных треков
S&M_PRESET_FX=8                          ; [Основная] запустить пресет для FX n выбранного трека (только MIDI/OSC) -- Max. = 8!
S&M_SELFX=8                              ; [Основная] выбрать FX n выбранных треков
S&M_SHOWFXCHAIN=8                        ; [Основная] показать цепочку FX выбранных треков, FX n
S&M_FLOATFX=8                            ; [Основная] плавающий FX n выбранных треков
S&M_UNFLOATFX=8                          ; [Основная] отменить плавающий FX n выбранных треков
S&M_TOGLFLOATFX=8                        ; [Основная] переключить плавающий FX n выбранных треков
S&M_MESETCCLANES=8                       ; [Основная] активный редактор MIDI - восстановить отображаемые дорожки CC, слот n
S&M_MESAVECCLANES=8                      ; [Основная] активный редактор MIDI - сохранить отображаемые дорожки CC, слот n
S&M_SETCCLANES_ME=8                      ; [MIDI-редактор] восстановить отображаемые дорожки CC, слот n
S&M_SAVECCLANES_ME=8                     ; [MIDI-редактор] сохранить отображаемые дорожки CC, слот n
S&M_SET_TRACK_GROUP=8                    ; [Основная] установить выбранные треки в группу n (флаги по умолчанию) -- Max. = 64!
S&M_OPEN_LIVECFG_MONITOR=8               ; [Основная] текущая настройка #n - открыть/закрыть окно мониторинга -- Max. = 8!
S&M_LIVECFG_APPLY=8                      ; [Основная] текущая настройка #n - применить н (только MIDI/OSC) -- Max. = 8!
S&M_LIVECFG_PRELOAD=8                    ; [Основная] текущая настройка #n - предзагрузка настройки (только MIDI/OSC) -- Max. = 8!
S&M_NEXT_LIVE_CFG=8                      ; [Основная] текущая настройка #n - применить следующую настройку -- Max. = 8!
S&M_PREVIOUS_LIVE_CFG=8                  ; [Основная] текущая настройка #n - применить предыдущую настройку -- Max. = 8!
S&M_PRELOAD_NEXT_LIVE_CFG=8              ; [Основная] текущая настройка #n - предзагрузка следующей настройки -- Max. = 8!
S&M_PRELOAD_PREVIOUS_LIVE_CFG=8          ; [Основная] текущая настройка #n - предзагрузка предыдущей настройки -- Max. = 8!
S&M_PRELOAD_LIVE_CFG=8                   ; [Основная] текущая настройка #n - применить предзагруженную настройку (заменять предзагрузка/текущая) -- Max. = 8!
S&M_LIVECFG_ON=0                         ; [Основная] текущая настройка #n - включить -- Max. = 8!
S&M_LIVECFG_OFF=0                        ; [Основная] текущая настройка #n - выключить -- Max. = 8!
S&M_LIVECFG_TGL=8                        ; [Основная] текущая настройка #n - вкл/выул -- Max. = 8!
S&M_LIVECFG_MUTEBUT_ON=0                 ; [Основная] текущая настройка #n - включить опцию 'выключить все, кроме активного трека' -- Max. = 8!
S&M_LIVECFG_MUTEBUT_OFF=0                ; [Основная] текущая настройка #n - выключить опцию 'выключить все, кроме активного трека' -- Max. = 8!
S&M_LIVECFG_MUTEBUT_TGL=8                ; [Основная] текущая настройка #n - переключить опцию 'выключить все, кроме активноого трека' -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_ON=0              ; [Основная] текущая настройка #n - включить опцию 'офлайн всё, кроме активных/предзагруженных треков' -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_OFF=0             ; [Основная] текущая настройка #n - выключить опцию 'офлайн всё, кроме активных/предзагруженных треков' -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_TGL=8             ; [Основная] текущая настройка #n - переключить опцию 'офлайн всё, кроме активных/предзагруженных треков' -- Max. = 8!
S&M_LIVECFG_DISARMBUT_ON=0               ; [Основная] текущая настройка #n - включить опцию 'деактивировать все, кроме активного трека' -- Max. = 8!
S&M_LIVECFG_DISARMBUT_OFF=0              ; [Основная] текущая настройка #n - выключить опцию 'деактивировать всё, кроме активного трека' -- Max. = 8!
S&M_LIVECFG_DISARMBUT_TGL=8              ; [Основная] текущая настройка #n - переключить опцию 'выключить всё, кроме активного трека' -- Max. = 8!
S&M_LIVECFG_CC123_ON=0                   ; [Основная] текущая настройка #n - включить опцию 'послать все ноты при переключении настроек' -- Max. = 8!
S&M_LIVECFG_CC123_OFF=0                  ; [Основная] текущая настройка #n - выключить опцию 'послать все ноты при переключении настроек' -- Max. = 8!
S&M_LIVECFG_CC123_TGL=8                  ; [Основная] текущая настройка #n - переключить опцию 'послать все ноты при переключении настроек' -- Max. = 8!
S&M_LIVECFG_FADES_ON=0                   ; [Основная] текущая настройка #n - включить микро-фейды -- Max. = 8!
S&M_LIVECFG_FADES_OFF=0                  ; [Основная] текущая настройка #n - выключить микро-фейды -- Max. = 8!
S&M_LIVECFG_FADES_TGL=8                  ; [Основная] текущая настройка #n - включить микро-фейды -- Max. = 8!
S&M_PLAY_RGN_PLAYLIST=4                  ; [Основная] плейлист регионов #n - проиграть
S&M_GOTO_MARKER=0                        ; [Основная] перейти к маркеру n (соблюдая плавный поиск)
S&M_GOTO_REGION=0                        ; [Основная] перейти к региону n (соблюдая плавный поиск)
S&M_GOTO_SEL_REGION=4                    ; [Основная] перейти к региону/выбор времени региона n (соблюдая плавный поиск)
S&M_DUMMY_TGL=8                          ; [Основная] переключить фиктивно на n
S&M_EXCL_TGL=4                           ; [Основная] переключить эксклюзивно на An
S&M_EXCL_TGL_B=4                         ; [Основная] переключить эксклюзивно на Bn
S&M_EXCL_TGL_C=4                         ; [Основная] переключить эксклюзивно на Cn
S&M_EXCL_TGL_D=4                         ; [Основная] переключить эксклюзивно на Dn
S&M_EXCL_TGL_E=0                         ; [Основная] переключить эксклюзивно на En
S&M_EXCL_TGL_F=0                         ; [Основная] переключить эксклюзивно на Fn
S&M_EXCL_TGL_G=0                         ; [Основная] переключить эксклюзивно на Gn
S&M_EXCL_TGL_H=0                         ; [Основная] переключить эксклюзивно на Hn
S&M_MIDI_INPUT_CH=16                     ; [Основная] задать вход MIDI выбранных треков на канал n -- Max. = 16!
S&M_MAP_MIDI_INPUT_CH=16                 ; [Основная] сопоставить вход MIDI выбранных треков с каналом n -- Max. = 16!
SWSSNAPSHOT_GET=12                       ; [Основная] вызвать снимок n
SWSSNAPSHOT_SAVE=12                      ; [Основная] сохранить как снимок n
SWS_SEL=32                               ; [Основная] выбрать только трек n
SWS_SAVETIME=5                           ; [Основная] сохранить выбор времени, слот n
SWS_RESTTIME=5                           ; [Основная] восстановить выбор времени, слот n
SWS_SAVELOOP=5                           ; [Основная] сохранить выбор цикла, слот n
SWS_RESTLOOP=5                           ; [Основная] восстановить выбор цикла, слот n
