





[Main_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Action1="$ULT View Setup|_S&M_EXCL_TGL1|40454|"
Action2="$ULT View Record|_S&M_EXCL_TGL2|40455|"
Action3="$ULT Ripple ALL|_XENAK__TOGGLERIPPLEALL|"
Action4="$ULT Ripple ONE|_XENAK_TOGGLERIPPLE1TRACK|"
Action5="$ULT View Edit|_S&M_EXCL_TGL3|40456|"
Action6="$ULT Routing 1|_S&M_EXCL_TGL_B1|_SWSSNAPSHOT_GET1|"
Action7="$ULT Routing 2|_S&M_EXCL_TGL_B2|_SWSSNAPSHOT_GET2|"
Action8="$ULT Routing 3|_S&M_EXCL_TGL_B3|_SWSSNAPSHOT_GET3|"
Action9="$ULT Routing 4|_S&M_EXCL_TGL_B4|_SWSSNAPSHOT_GET4|"
Action10="ULT Mute|_RSc213922f9dfbd2bd9f71b14ff4cd6875c8abd845|"
Action11="ULT View Storyboard|_S&M_EXCL_TGL4|40457|"
Action12="$Custom:track show/hide|_13f9675bf1e59940817c9d8012c75ee4|IF NOT|ENDIF|!|_13f9675bf1e59940817c9d8012c75ee4|IF|ENDIF|"
Action13="#B/C Layout|40454|!|40455|"
Action14="$Narrow/Default|40460|!|40462|"
Action15="#Fx Bypass|40342|!|40343|"
Action16="$Mixing View|!|40457|"
Nb_Actions=16
Version=3
[MainAlt_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Nb_Actions=0
Version=3
[MediaEx_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Nb_Actions=0
Version=3
[ME_Piano_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Nb_Actions=0
Version=3
[ME_List_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Nb_Actions=0
Version=3
[ME_Inline_Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead
Nb_Actions=0
Version=3
